### ISSUE TITLE
RE:README.md, by additions do you mean a new WTF issue

### ISSUE THREAD

**Issue by matchew** [mdo/wtf-html-css#11]
Because my pet peeve is no block level elements within a paragraph. Why would I want that? I work in publishing, and we often have documents where the original text was something like:

```
<p> Some paragraph text

<blockquote> obvious block quoted material from another source</blockquote>

a continuation of the same parent paragraph.</p>
```

This causes problems when it comes to the HTML. Part of our office are old school SGML guys who preach the wonder that is XML. But the resulting HTML from this is invalid and the browsers through a fit as it will be translated as follows:

```
<p> Some paragraph text</p>

<blockquote> obvious block quoted material from another source</blockquote>

a continuation of the same parent paragraph.
```

maybe I'm just not finding the right XSLT for my situation, or maybe I am still won over on the argument that my HTML should be semantic. If it is all the same paragraph shouldn't it be contained within the same p? Secunia with this solution I now have to use something like data-id, because id's need to be unique, but we need to associate the three parts together. It's really a WTF situation.

**Comment by mdo** [comment]
For the purposes of this project, that looks wrong, but there's nothing for me to add to the list about this. Good luck getting them to move on! <3
