### ISSUE TITLE
Reduce vulgar language

### ISSUE THREAD

**Issue by philip-peterson** [mdo/wtf-html-css#15]
While it's a great idea and resource, one problem with this site is that it has some vulgar language on it. Not that I'm for this type of censorship in general, but I would like to link to this resource (e.g. to co-workers) but owing to the language, it would probably be inappropriate. Others (in Hacker News comments) have expressed this sentiment too, so I'm not unique in this regard. It seems like an unnecessary barrier to dissemination.

**Comment by mdo** [comment]
Yeah, I swear a lot. I generally don't see it as a problem, but I am aware that a large number of folks have stronger opinions on the matter. My typical reply to this would be "Fuck that," but that's generally not helpful and dismisses folks' feedback.

I've removed two instances of _shit_ in b3d62f85211f857780a21af4f3cbb83de0a3f144 and tweaked some of the instances of _fuck_ to be less harsh. Should help some.
