### ISSUE TITLE
IE≤9 doctype

### ISSUE THREAD

**Issue by mdo** [mdo/wtf-html-css#2]
No doctype triggers quirks mode for IE?

Source: https://twitter.com/bundyo/status/448001482601025536

**Comment by Garbee** [comment]
Yup, Henri Sivonen has a very [detailed post](https://hsivonen.fi/doctype/) about browser modes. That may want to get linked to as a reference for the interested.

**Comment by mdo** [comment]
This is basically covered following a few edits made earlier.
