### ISSUE TITLE
white-space vs nowrap vs pre-wrap vs pre-line

### ISSUE THREAD

**Issue by laughinghan** [mdo/wtf-html-css#20]
Is this only about things that require workarounds? One really annoying WTF for me is the inconsistent dashes between `white-space` ("whitespace" is a word, who the fuck uses a dash?!), `nowrap` (they're 2 separate words! "nowrap" isn't a word! This is where there _should_ be a dash!), `pre-wrap`, and `pre-line` (unlike "no-", "pre-" is an actual prefix and not using a dash possibly makes sense).

The workaround is just using the specced keywords, of course.

**Comment by mdo** [comment]
I don't see much of a need to document anything here. This isn't much of a common misconception as it is a question of remembering what properties are named what.
