### ISSUE TITLE
Firefox still needs a reset for button elements

### ISSUE THREAD

**Issue by fvsch** [mdo/wtf-html-css#24]
In “Firefox and `<input>` buttons”, the advice “Just use the `<button>` element” is wrong.

Firefox does add a pseudo-element in the shadow dom (I think) of `button` elements, and the fix that is mentioned for `<input>` buttons should be applied to `<button>` elements as well.

Last tested on http://fvsch.com/code/button-css/ with Firefox 30 (Aurora) on OS X.
How to reproduce: go to that page using Firefox 30-, use the Style Editor in the devtools, go to the inline stylesheet and remove this code:

``` css
button::-moz-focus-inner {
  padding: 0;
  border: none;
}
```

The black button should expand by a few pixels. In my test it was 239×27 pixels with the reset, and 245×29 pixels without the reset.

**Comment by mdo** [comment]
There's a paragraph at the end of that section:

> Good news! It looks like a fix for this might be coming in Firefox 30. That's good news for our future selves, but be aware this doesn't fix older versions.

That's a separate issue though from the code snippet that's included there. I've pushed a change to split out the two problems in that section to properly mention everything. Let me know if that helps.
