### ISSUE TITLE
Gradients cannot be transitioned

### ISSUE THREAD

**Issue by mlettini** [mdo/wtf-html-css#36]
Gradients won't transition to other gradients, some folks might not know and think their code is wrong when it isn't working.

A possible workaround is to make the background color of the element a solid color, and use `:before` to add a transparent gradient above the element. Then you need only transition the background from one solid color to another.

**Comment by davidpustai** [comment]
Or hack it this way http://codepen.io/lonekorean/pen/HiJDw, if it's a linear gradient.
