### ISSUE TITLE
Collapsing margins

### ISSUE THREAD

**Issue by gwythen** [mdo/wtf-html-css#47]
Collapsing margins can cause unwanted behaviors, such as pushing a parent down when a top margin is applied to one of its children. Like in this example:

http://stackoverflow.com/questions/1394724/css-margin-top-when-parents-got-no-border

A common solution is to apply overflow: hidden (or overflow:auto) to the container element, in order to force the creation of a new Block Formatting Context, thus preventing margins from collapsing.

**Comment by mdo** [comment]
I've mentioned that margins can and will collapse: http://wtfhtmlcss.com/#vertical-margins-collapse.

I will not advocate folks reset that behavior with unnecessary overrides though. That sounds like a horrible idea with good intentions that adds unexpected complications down the line.

**Comment by gwythen** [comment]
Totally agree. I just think it might be useful to have an hint at what behaviors this is producing (e.g. in case of margin on children elements).
