### ISSUE TITLE
transparent in Firefox css gradients

### ISSUE THREAD

**Issue by davidpustai** [mdo/wtf-html-css#50]
When you use the `transparent` as one of the values in css gradient (linear or radial), it doesn't acts as one would expected. Only appears in Firefox.

E. g. `linear-gradient(to right, #ccc, transparent 20%, transparent 80%, #ccc);` creates gray full-width background instead of fading on sides. It works if you use `rgba(204, 204, 204, 0)` instead of `transparent`, but doesn't if you use `transparent` itself, or even for example `rgba(0, 0, 0, 0)`.

This was quite a WTF moment for me, so I'm mentioning it here.

Please correct me if I'm wrong and this is desired behavior.

**Comment by cvrebert** [comment]
> Only appears in Firefox.

On which OS did you test?
For context, which other browsers did you try?
