### ISSUE TITLE
IE6 & inline floats

### ISSUE THREAD

**Issue by peduarte** [mdo/wtf-html-css#7]
Hello!

Just a quick note about this:

> Fun fact: Years ago, we had to set display: inline; for floats to work properly in IE6. However, those days have long passed.

Floats would work fine in IE6, the use of `display: inline;` was to avoid the famous [Double Margin](http://www.positioniseverything.net/explorer/doubled-margin.html) bug.

But yeah, those days have long passed. Thank ***\* for that.

**Comment by mdo** [comment]
Gah, yes, I forgot to mention the double margin bug. Thanks—just updated it!
